
knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la barre de pagination
    default_options:
        page_name: page                # Nom du paramètre de requête pour la page
        sort_field_name: sort          # Nom du paramètre de requête pour le tri
        sort_direction_name: direction # Nom du paramètre de requête pour la direction de tri
        distinct: true                 # Si true, la pagination est effectuée sur des éléments distincts
