vich_uploader:
    db_driver: orm
    mappings:
        reward_images:
            uri_prefix: '/images/rewards'
            upload_destination: '%kernel.project_dir%/public/images/rewards'
            namer: App\Naming\CustomNamer
        gif_images:
            uri_prefix: '/images/gifs'
            upload_destination: '%kernel.project_dir%/public/images/gifs'
            namer: App\Naming\CustomNamer